### PR TITLE
(cinebench) Update and fix package

### PR DESCRIPTION
**Pull request by TheCakeIsNaOH**

### CODE REVIEW

**Comment by Windos** [comment]
Thanks for looking at this @TheCakeIsNaOH! Can I confirm what I can I'm seeing with you?

As is, I get the message you mentioned about not being able to get the headers, but then I also get an error about modifying the User-Agent.

image

Commenting out the User-Agent header (and leaving everything else) results in the install proceeding for me.

image

This is Choco CLI 2.2.2 run from PowerShell 7.4.1. I also saw this running from PowerShell (though, once the zip has been downloaded, it doesn't download it again so I had to clean that up from the temp files to test.)

image

**Comment by TheCakeIsNaOH** [comment]
I was not seeing the User-Agent error when testing, but I was testing on Open Source Chocolatey CLI. When I test on C4B, I'm seeing the same User-Agent error. It looks like a bug/oversite in the C4B implementation of that cmdlet. 

Since it does seem to work without the User-Agent at the moment, I'll remove it from the `$options`.

**Comment by Windos** [comment]
I didn't think to check without the licensed extension, I'll raise/look for an issue about the User-Agent behaviour over there.

**Review by Windos — APPROVED** [review]
LGTM, thanks for working on this @TheCakeIsNaOH!

**Pull request merged**
